version: '3'
services:
  redis-db:
    image: redis
    ports:
      - 6379:6379
  stonks-svc:
    build: .
    environment:
      APP_PORT: 9001
      STONK_REDIS_HOST: redis-db:6379
      TRADING_API_KEY: REPLACE-VALUE
    ports:
      - 9001:9001
    depends_on:
      - redis-db