// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stonks.proto

package stonks

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetFavoritesRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFavoritesRequest) Reset()         { *m = GetFavoritesRequest{} }
func (m *GetFavoritesRequest) String() string { return proto.CompactTextString(m) }
func (*GetFavoritesRequest) ProtoMessage()    {}
func (*GetFavoritesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0efca0388d648e, []int{0}
}

func (m *GetFavoritesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFavoritesRequest.Unmarshal(m, b)
}
func (m *GetFavoritesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFavoritesRequest.Marshal(b, m, deterministic)
}
func (m *GetFavoritesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFavoritesRequest.Merge(m, src)
}
func (m *GetFavoritesRequest) XXX_Size() int {
	return xxx_messageInfo_GetFavoritesRequest.Size(m)
}
func (m *GetFavoritesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFavoritesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFavoritesRequest proto.InternalMessageInfo

func (m *GetFavoritesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetFavoritesResponse struct {
	Stonks               []*Stonk `protobuf:"bytes,1,rep,name=stonks,proto3" json:"stonks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFavoritesResponse) Reset()         { *m = GetFavoritesResponse{} }
func (m *GetFavoritesResponse) String() string { return proto.CompactTextString(m) }
func (*GetFavoritesResponse) ProtoMessage()    {}
func (*GetFavoritesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0efca0388d648e, []int{1}
}

func (m *GetFavoritesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFavoritesResponse.Unmarshal(m, b)
}
func (m *GetFavoritesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFavoritesResponse.Marshal(b, m, deterministic)
}
func (m *GetFavoritesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFavoritesResponse.Merge(m, src)
}
func (m *GetFavoritesResponse) XXX_Size() int {
	return xxx_messageInfo_GetFavoritesResponse.Size(m)
}
func (m *GetFavoritesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFavoritesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFavoritesResponse proto.InternalMessageInfo

func (m *GetFavoritesResponse) GetStonks() []*Stonk {
	if m != nil {
		return m.Stonks
	}
	return nil
}

type Stonk struct {
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	//UTC time stamp
	// string time_added = 2;
	// in USD
	CurrentPrice         float64  `protobuf:"fixed64,2,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	FiftyTwoWeekHigh     float64  `protobuf:"fixed64,4,opt,name=fifty_two_week_high,json=fiftyTwoWeekHigh,proto3" json:"fifty_two_week_high,omitempty"`
	FiftyTwoWeekLow      float64  `protobuf:"fixed64,5,opt,name=fifty_two_week_low,json=fiftyTwoWeekLow,proto3" json:"fifty_two_week_low,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stonk) Reset()         { *m = Stonk{} }
func (m *Stonk) String() string { return proto.CompactTextString(m) }
func (*Stonk) ProtoMessage()    {}
func (*Stonk) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0efca0388d648e, []int{2}
}

func (m *Stonk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stonk.Unmarshal(m, b)
}
func (m *Stonk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stonk.Marshal(b, m, deterministic)
}
func (m *Stonk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stonk.Merge(m, src)
}
func (m *Stonk) XXX_Size() int {
	return xxx_messageInfo_Stonk.Size(m)
}
func (m *Stonk) XXX_DiscardUnknown() {
	xxx_messageInfo_Stonk.DiscardUnknown(m)
}

var xxx_messageInfo_Stonk proto.InternalMessageInfo

func (m *Stonk) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Stonk) GetCurrentPrice() float64 {
	if m != nil {
		return m.CurrentPrice
	}
	return 0
}

func (m *Stonk) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Stonk) GetFiftyTwoWeekHigh() float64 {
	if m != nil {
		return m.FiftyTwoWeekHigh
	}
	return 0
}

func (m *Stonk) GetFiftyTwoWeekLow() float64 {
	if m != nil {
		return m.FiftyTwoWeekLow
	}
	return 0
}

type CreateFavoritesRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFavoritesRequest) Reset()         { *m = CreateFavoritesRequest{} }
func (m *CreateFavoritesRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFavoritesRequest) ProtoMessage()    {}
func (*CreateFavoritesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0efca0388d648e, []int{3}
}

func (m *CreateFavoritesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFavoritesRequest.Unmarshal(m, b)
}
func (m *CreateFavoritesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFavoritesRequest.Marshal(b, m, deterministic)
}
func (m *CreateFavoritesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFavoritesRequest.Merge(m, src)
}
func (m *CreateFavoritesRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFavoritesRequest.Size(m)
}
func (m *CreateFavoritesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFavoritesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFavoritesRequest proto.InternalMessageInfo

func (m *CreateFavoritesRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CreateFavoritesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateFavoritesResponse struct {
	Stonk                *Stonk   `protobuf:"bytes,1,opt,name=stonk,proto3" json:"stonk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFavoritesResponse) Reset()         { *m = CreateFavoritesResponse{} }
func (m *CreateFavoritesResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFavoritesResponse) ProtoMessage()    {}
func (*CreateFavoritesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0efca0388d648e, []int{4}
}

func (m *CreateFavoritesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFavoritesResponse.Unmarshal(m, b)
}
func (m *CreateFavoritesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFavoritesResponse.Marshal(b, m, deterministic)
}
func (m *CreateFavoritesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFavoritesResponse.Merge(m, src)
}
func (m *CreateFavoritesResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFavoritesResponse.Size(m)
}
func (m *CreateFavoritesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFavoritesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFavoritesResponse proto.InternalMessageInfo

func (m *CreateFavoritesResponse) GetStonk() *Stonk {
	if m != nil {
		return m.Stonk
	}
	return nil
}

type DeleteFavoritesRequest struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFavoritesRequest) Reset()         { *m = DeleteFavoritesRequest{} }
func (m *DeleteFavoritesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFavoritesRequest) ProtoMessage()    {}
func (*DeleteFavoritesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0efca0388d648e, []int{5}
}

func (m *DeleteFavoritesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFavoritesRequest.Unmarshal(m, b)
}
func (m *DeleteFavoritesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFavoritesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFavoritesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFavoritesRequest.Merge(m, src)
}
func (m *DeleteFavoritesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFavoritesRequest.Size(m)
}
func (m *DeleteFavoritesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFavoritesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFavoritesRequest proto.InternalMessageInfo

func (m *DeleteFavoritesRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *DeleteFavoritesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteFavoritesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFavoritesResponse) Reset()         { *m = DeleteFavoritesResponse{} }
func (m *DeleteFavoritesResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFavoritesResponse) ProtoMessage()    {}
func (*DeleteFavoritesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff0efca0388d648e, []int{6}
}

func (m *DeleteFavoritesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFavoritesResponse.Unmarshal(m, b)
}
func (m *DeleteFavoritesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFavoritesResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFavoritesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFavoritesResponse.Merge(m, src)
}
func (m *DeleteFavoritesResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFavoritesResponse.Size(m)
}
func (m *DeleteFavoritesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFavoritesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFavoritesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetFavoritesRequest)(nil), "stonks.GetFavoritesRequest")
	proto.RegisterType((*GetFavoritesResponse)(nil), "stonks.GetFavoritesResponse")
	proto.RegisterType((*Stonk)(nil), "stonks.Stonk")
	proto.RegisterType((*CreateFavoritesRequest)(nil), "stonks.CreateFavoritesRequest")
	proto.RegisterType((*CreateFavoritesResponse)(nil), "stonks.CreateFavoritesResponse")
	proto.RegisterType((*DeleteFavoritesRequest)(nil), "stonks.DeleteFavoritesRequest")
	proto.RegisterType((*DeleteFavoritesResponse)(nil), "stonks.DeleteFavoritesResponse")
}

func init() { proto.RegisterFile("stonks.proto", fileDescriptor_ff0efca0388d648e) }

var fileDescriptor_ff0efca0388d648e = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xdd, 0x4e, 0xe2, 0x40,
	0x14, 0xc7, 0x29, 0x1f, 0xdd, 0xec, 0x59, 0xd8, 0xdd, 0x0c, 0x1b, 0xe8, 0x82, 0x1f, 0xa4, 0xc4,
	0x84, 0xc4, 0x00, 0x09, 0x5e, 0xeb, 0x85, 0x1a, 0x95, 0xe8, 0x85, 0x29, 0x26, 0x26, 0xde, 0x34,
	0x7c, 0x1c, 0xa0, 0x01, 0x99, 0x3a, 0x33, 0xd0, 0xf0, 0x02, 0x3e, 0x91, 0x0f, 0x68, 0x3a, 0xd3,
	0x86, 0xd6, 0x96, 0x3b, 0xaf, 0xda, 0x73, 0xce, 0xff, 0xfc, 0xcf, 0x99, 0x5f, 0x3b, 0x50, 0xe4,
	0x82, 0xae, 0x16, 0xbc, 0xe3, 0x32, 0x2a, 0x28, 0xd1, 0x55, 0x64, 0x76, 0xa0, 0x7c, 0x8b, 0xe2,
	0x66, 0xb8, 0xa1, 0xcc, 0x11, 0xc8, 0x2d, 0x7c, 0x5b, 0x23, 0x17, 0xa4, 0x0a, 0x3f, 0xd6, 0x1c,
	0x99, 0xed, 0x4c, 0x0c, 0xad, 0xa1, 0xb5, 0x7e, 0x5a, 0xba, 0x1f, 0xf6, 0x27, 0xe6, 0x39, 0xfc,
	0x8b, 0xeb, 0xb9, 0x4b, 0x57, 0x1c, 0xc9, 0x09, 0x04, 0x8e, 0x86, 0xd6, 0xc8, 0xb5, 0x7e, 0xf5,
	0x4a, 0x9d, 0x60, 0xdc, 0xc0, 0x7f, 0x58, 0xe1, 0xb8, 0x0f, 0x0d, 0x0a, 0x32, 0x43, 0x2a, 0xa0,
	0xf3, 0xed, 0xeb, 0x88, 0x2e, 0xc3, 0x01, 0x2a, 0x22, 0x4d, 0x28, 0x8d, 0xd7, 0x8c, 0xe1, 0x4a,
	0xd8, 0x2e, 0x73, 0xc6, 0x68, 0x64, 0x1b, 0x5a, 0x4b, 0xb3, 0x8a, 0x41, 0xf2, 0xd1, 0xcf, 0x11,
	0x02, 0x79, 0xb1, 0x75, 0xd1, 0xc8, 0xc9, 0x56, 0xf9, 0x4e, 0xda, 0x50, 0x9e, 0x3a, 0x53, 0xb1,
	0xb5, 0x85, 0x47, 0x6d, 0x0f, 0x71, 0x61, 0xcf, 0x9d, 0xd9, 0xdc, 0xc8, 0xcb, 0xf6, 0xbf, 0xb2,
	0xf4, 0xe4, 0xd1, 0x67, 0xc4, 0xc5, 0x9d, 0x33, 0x9b, 0x93, 0x53, 0x20, 0x5f, 0xe4, 0x4b, 0xea,
	0x19, 0x05, 0xa9, 0xfe, 0x13, 0x55, 0x3f, 0x50, 0xcf, 0xec, 0x43, 0xe5, 0x8a, 0xe1, 0x50, 0x60,
	0x02, 0xd4, 0xbe, 0x63, 0x44, 0x00, 0x66, 0x63, 0x00, 0x2f, 0xa0, 0x9a, 0xb0, 0x0a, 0x18, 0x36,
	0xa1, 0x20, 0x31, 0x49, 0xab, 0x04, 0x42, 0x55, 0xf3, 0x57, 0xb9, 0xc6, 0x25, 0x7e, 0xc7, 0x2a,
	0xff, 0xa1, 0x9a, 0xb0, 0x52, 0xab, 0xf4, 0xde, 0xb3, 0x50, 0x92, 0x63, 0xf9, 0x00, 0xd9, 0xc6,
	0x47, 0x7e, 0x0f, 0xc5, 0xe8, 0x87, 0x27, 0xf5, 0x70, 0xbb, 0x94, 0xdf, 0xa7, 0x76, 0x90, 0x5e,
	0x54, 0xe6, 0x66, 0x86, 0x0c, 0xe0, 0x77, 0x1c, 0x02, 0x39, 0x0a, 0x3b, 0xd2, 0x39, 0xd7, 0x8e,
	0xf7, 0xd6, 0xa3, 0xa6, 0xf1, 0xe3, 0xec, 0x4c, 0xd3, 0x89, 0xed, 0x4c, 0xf7, 0x60, 0x30, 0x33,
	0x97, 0x87, 0x2f, 0x75, 0xa5, 0x69, 0x73, 0x05, 0xa2, 0x2b, 0xef, 0x4f, 0x57, 0x25, 0x47, 0xba,
	0x8c, 0xce, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x59, 0x0b, 0x4c, 0x5d, 0x5d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StonksServiceClient is the client API for StonksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StonksServiceClient interface {
	GetFavorites(ctx context.Context, in *GetFavoritesRequest, opts ...grpc.CallOption) (*GetFavoritesResponse, error)
	CreateFavorite(ctx context.Context, in *CreateFavoritesRequest, opts ...grpc.CallOption) (*CreateFavoritesResponse, error)
	DeleteFavorite(ctx context.Context, in *DeleteFavoritesRequest, opts ...grpc.CallOption) (*DeleteFavoritesResponse, error)
}

type stonksServiceClient struct {
	cc *grpc.ClientConn
}

func NewStonksServiceClient(cc *grpc.ClientConn) StonksServiceClient {
	return &stonksServiceClient{cc}
}

func (c *stonksServiceClient) GetFavorites(ctx context.Context, in *GetFavoritesRequest, opts ...grpc.CallOption) (*GetFavoritesResponse, error) {
	out := new(GetFavoritesResponse)
	err := c.cc.Invoke(ctx, "/stonks.StonksService/GetFavorites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stonksServiceClient) CreateFavorite(ctx context.Context, in *CreateFavoritesRequest, opts ...grpc.CallOption) (*CreateFavoritesResponse, error) {
	out := new(CreateFavoritesResponse)
	err := c.cc.Invoke(ctx, "/stonks.StonksService/CreateFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stonksServiceClient) DeleteFavorite(ctx context.Context, in *DeleteFavoritesRequest, opts ...grpc.CallOption) (*DeleteFavoritesResponse, error) {
	out := new(DeleteFavoritesResponse)
	err := c.cc.Invoke(ctx, "/stonks.StonksService/DeleteFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StonksServiceServer is the server API for StonksService service.
type StonksServiceServer interface {
	GetFavorites(context.Context, *GetFavoritesRequest) (*GetFavoritesResponse, error)
	CreateFavorite(context.Context, *CreateFavoritesRequest) (*CreateFavoritesResponse, error)
	DeleteFavorite(context.Context, *DeleteFavoritesRequest) (*DeleteFavoritesResponse, error)
}

// UnimplementedStonksServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStonksServiceServer struct {
}

func (*UnimplementedStonksServiceServer) GetFavorites(ctx context.Context, req *GetFavoritesRequest) (*GetFavoritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFavorites not implemented")
}
func (*UnimplementedStonksServiceServer) CreateFavorite(ctx context.Context, req *CreateFavoritesRequest) (*CreateFavoritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFavorite not implemented")
}
func (*UnimplementedStonksServiceServer) DeleteFavorite(ctx context.Context, req *DeleteFavoritesRequest) (*DeleteFavoritesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFavorite not implemented")
}

func RegisterStonksServiceServer(s *grpc.Server, srv StonksServiceServer) {
	s.RegisterService(&_StonksService_serviceDesc, srv)
}

func _StonksService_GetFavorites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StonksServiceServer).GetFavorites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonks.StonksService/GetFavorites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StonksServiceServer).GetFavorites(ctx, req.(*GetFavoritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StonksService_CreateFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFavoritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StonksServiceServer).CreateFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonks.StonksService/CreateFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StonksServiceServer).CreateFavorite(ctx, req.(*CreateFavoritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StonksService_DeleteFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavoritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StonksServiceServer).DeleteFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonks.StonksService/DeleteFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StonksServiceServer).DeleteFavorite(ctx, req.(*DeleteFavoritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StonksService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stonks.StonksService",
	HandlerType: (*StonksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFavorites",
			Handler:    _StonksService_GetFavorites_Handler,
		},
		{
			MethodName: "CreateFavorite",
			Handler:    _StonksService_CreateFavorite_Handler,
		},
		{
			MethodName: "DeleteFavorite",
			Handler:    _StonksService_DeleteFavorite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stonks.proto",
}
